---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceAccount - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: serviceAccount is not created by default
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          any: true

  - it: serviceAccounts are enabled by default
    set:
      serviceAccount:
        main: {}
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name
          any: true

  - it: serviceAccounts can be disabled
    set:
      serviceAccount:
        default:
          enabled: false
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          name: release-name
          any: true

  - it: multiple serviceAccounts can be enabled
    set:
      controllers.main.serviceAccount.identifier: myAccount
      serviceAccount:
        myAccount: {}
        mySA: {}
        mySA2:
          enabled: false
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name-myaccount
          any: true
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          name: release-name-mysa2
          any: true
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-mysa2-sa-token
          any: true
